### ISSUE TITLE
is there any to ignore the SpotlightException in your tool

### ISSUE THREAD

**Issue by zixufang** [aolieman/pyspotlight#4]
hi, I came across a problem when using your tool.
I have to process a list of sentence. Every sentence have to be linked to the API. SO I don't want to the SpotlightException to interrupt the whole process.
is there any to ignore the SpotlightException?

here is my code:
```
with open('/home/tfang/data/corpus/mr.clean.txt', "r") as f:
	for line in f.readlines():
		doc_list.append(line.strip())
		text = line.strip()

		entity_current = []

		annotations = spotlight.annotate('http://localhost:2222/rest/annotate', \
		text, confidence=0.5, support=0)
		
		if annotations !=None:
			for resource_i in annotations:
				entity_current.append(resource_i["URI"][28:])
			print(entity_current)
		entity_list.append(entity_current)
with open("/home/tfang/data/process/entity_mr", "wb") as f:
	json.dump(entity_list, f)

```
here is the output in the console:
`Traceback (most recent call last):
  File "entity_link.py", line 21, in <module>
    text, confidence=0.5, support=0)
  File "/home/tfang/anaconda3/envs/torch1.6/lib/python3.6/site-packages/spotlight/__init__.py", line 196, in annotate
    'No Resources found in spotlight response: %s' % pydict
spotlight.SpotlightException: No Resources found in spotlight response: {'@text': 'idiotic and ugly', '@confidence': '0.5', '@support': '0', '@types': '', '@sparql': '', '@policy': 'whitelist'}`

**Comment by zixufang** [comment]
Sorry to bother you.
I know now how to do it.
